export default {
    'add':{ //新增
        'colors':'primary',
        'name':'新增',
        'name_zh_tw':'繁体',
        'name_en_us':'英文',
        'hotkey':'alt+n',
        'className':'ac-btns-add'
    },
    'search':{//查询
        'colors':'primary',
        'name':'查询',
        'hotkey':'ctrl+enter',
        'className':'ac-btns-search'
    },
    'clear':{//清空
        'colors':'write',
        'name':'清空',
        'hotkey':'ctrl+r',
        'className':'ac-btns-clear'
    },
    'export':{//导出
        'colors':'write',
        'name':'导出',
        'hotkey':'',
        'className':'ac-btns-export'
    },
    'save':{//保存
        'colors':'primary',
        'name':'保存',
        'hotkey':'',
        'className':'ac-btns-save'
    },
    'cancel':{//取消
        'colors':'write',
        'name':'取消',
        'hotkey':'',
        'className':'ac-btns-cancel'
    },
    'update':{//编辑
        'colors':'write',
        'name':'编辑',
        'hotkey':'',
        'className':'ac-btns-update'
    },
    'delete':{//删除
        'colors':'write',
        'name':'删除',
        'hotkey':'',
        'className':'ac-btns-delete'
    },
    'pbmsubmit':{//提交
        'colors':'write',
        'name':'提交',
        'hotkey':'',
        'className':'ac-btns-pbmsubmit'
    },
    'pbmcancle':{//撤回
        'colors':'write',
        'name':'撤回',
        'hotkey':'',
        'className':'ac-btns-pbmcancle'
    },
    'pbmapprove':{//审批
        'colors':'write',
        'name':'审批',
        'hotkey':'',
        'className':'ac-btns-pbmapprove'
    },
    'printpreview':{//打印预览
        'colors':'write',
        'name':'打印预览',
        'className':'ac-btns-printpreview'
    },
    'printpreview':{//打印设计
        'colors':'write',
        'name':'打印设计',
        'className':'ac-btns-printpreview'
    },
    'printdesign':{//打印设计
        'colors':'write',
        'name':'打印设计',
        'className':'ac-btns-printdesign'
    },
    'upload':{//上传文件
        'colors':'write',
        'name':'上传文件',
        'className':'ac-btns-upload'
    },
    'addRow':{//增行
        'colors':'write',
        'name':'增行',
        'className':'ac-btns-addRow'
    },
    'delRow':{//删行
        'colors':'write',
        'name':'删行',
        'className':'ac-btns-delRow'
    },
    'copyRow':{//复制行
        'colors':'write',
        'name':'复制行',
        'className':'ac-btns-copyRow'
    },
    'max':{//最大化
        'colors':'write',
        'name':'max',
        'className':'ac-btns-max'
    },
    'copyToEnd':{//粘贴至末行
        'colors':'write',
        'name':'粘贴至末行',
        'className':'ac-btns-copyToEnd'
    },
}

